image:https://github.com/HOME-programming-lab/SP2022Group3/actions/workflows/maven.yml/badge.svg["CI Build", link="https://github.com/HOME-programming-lab/SP2022Group3/actions"]

= Möbelhausmanagementprojekt- spitzenklassesoftware (MHMPS)

Dies ist eine persönliche Kopie des Gruppenprojekts, die ursprünglich auf https://github.com/HOME-programming-lab/SP2022Group3/actions veröffentlicht wurde, jetzt aber auf privat eingestellt ist.


Die Möbel-Hunger-Kette möchte das frisch erworbene Unternehmen Möbel-Hier mit einer Software für Bestellverwaltung, Lagerhaltung und Auslieferung ausstatten. Diese trägt den Arbeitstitel MHMPS (Möbelhausmanagementprojektspitzenklassesoftware).

Kunden können aus einem Katalog einzelne Möbel oder Möbel-Kombinationen aus Einzelmöbeln oder Möbelteilen (Bundles) wählen. Ihre Bestellungen werden am Telefon von einem Mitarbeiter entgegengenommen und in der Bestellverwaltung abgelegt. Für die zügige Belieferung der Kunden unterhält Möbel-Hier ein Lager, das ebenfalls durch MHMPS verwaltet werden soll. Für die Auslieferung kann der Kunde zwischen Selbstabholung mit eigenem oder von Möbel-Hier geliehenem LKW oder Anlieferung durch Möbel-Hier wählen. Für die Geschäftsführung soll ein Überblic über die Möbelverkäufe einzelner Lieferanten im monatlichen Vergleich erstellt werden.

Das Software-Projekt verwendet Java, Salespoint und Sprint.

Folgendes ist im Repository enthalten:

* eine minimale Java 11 Webanwendung auf der Basis von Spring Boot und Salespoint (siehe die Ordner `src/main/java` und `src/test/java`)
* Prototypen für die geplante Anwendung

== Die folgenden Dokumente sind enthalten

* link:src/main/asciidoc/protocols[Meeting-Protokolle]
* link:src/main/asciidoc/pflichtenheft.adoc[Anforderungsspezifikation (Pflichtenheft)]
* link:src/main/asciidoc/developer_documentation.adoc[Entwicklerdokumentation (Software-Entwurf)]

== Struktur des Repositories

Grundsätzlich entspricht die Projektstruktur dem Maven-Standardlayout. Sie finden daher die meisten wichtigen Artefakte unter `src/`:

  src/
  ├── main/
  │   ├── asciidoc/   -- Hier befinden sich die Nachweisdokumente und Anwendungsdokumentation (Asciidoc format)
  │   ├── java/       -- Hier befinden sich die Java-Quelldateien, in Java-Packages organisiert.
  │   └── resources/  -- Statische Elemente (wie z.B. Abbildungen und Stylesheets), https://www.thymeleaf.org/[Thymeleaf-Templates], etc.
  └── test/
      └── java/       -- Die automatischen Unit- und Integrationstests werden in einem separatem Verzeichnis abgelegt. Das ermöglicht es uns, die Testfälle sauber von der eigentlichen Anwendung zu trennen. Die Testfälle werden am Besten mit dem link:https://junit.org/junit5/[JUnit-Framework] erstellt.

Weitere Dateien, über die Sie stolpern werden:

* `.gitignore`          -- In dieser Datei können Sie Git mitteilen, welche Dateien und Verzeichnisse nicht in das Repository eingecheckt werden sollen.
* `pom.xml`             -- Dies ist die Maven Build-Spezifikation, Informationen zu diesem Format finden Sie in der link:https://maven.apache.org/index.html[Maven-Dokumentation].
* `.editorconfig`       -- Erlaubt es, verschiedene Editoren mit identischen Grundeinstellungen zu versehen, z.B. bezüglich des Datei-Encodings, welches Sie standardmäßig am Besten auf UTF-8 stellen.
* `mvnw` und `mvnw.cmd` -- Shell-Skripte, die Maven herunterladen, installieren und ausführen, wenn es sich noch nicht auf Ihrem System befindet.

== Ausführen der Anwendung

* In der IDE (Eclipse): suchen Sie `Application.java`, Rechtsklick auf das Projekt und dann "Run As > Java Application"
* Von der Kommandozeile: `./mvnw spring-boot:run` ausführen

== Paketierung

Java-Anwendungen werden in der Regel als JAR-Dateien gepackt und ausgeliefert. Eine JAR-Datei kann von Javas virtueller Maschine direkt verarbeitet und ausgeführt werden, vorrausgesetzt in der JAR-Datei befindet sich eine Klasse mit einer `main`-Funktion. 

Maven unterstützt Sie auch bei der Erstellung solcher Paketierungen:

* Mittels `./mvnw clean package` erstellen Sie eine JAR-Datei im Build-Verzeichnis `target/`. 
* Die erstelle JAR-Datei kann dann mittels `java -jar $jarName` ausgeführt werden (`$jarName` steht für den Namen der erstellten Datei).
