= Protokoll Gruppe 3

Treffen am 25.04.2022

Ort:      Hochschule Merseburg +
Beginn:   14:45 Uhr +
Ende:     15:30 Uhr

__Schriftführer:__ Robert Peter

*Nächstes Treffen:* +
28.04.2022, 12:30 Uhr, Hochschule Merseburg

__Teilnehmer:__

- Robert Peter
- Thomas Berthold
- Anas Lasri
- Younes Achahba
- Duc Hieu Le
- Steve Kuhnt
- Prof. Karol

== Bemerkungen

Das Pflichtenheft wurde abgegeben, es wurde jedoch um Nachbesserungen gebeten.
Punkte die noch überarbeitet werden müssen:

* Stakeholder an Projekt Möbelgeschäft anpassen 
* im Top-Level-Diagramm Pfeile vom Mitarbeiter zu Katalog einfügen 
* Kunden- / Mitarbeiterverwaltung nachtragen 
* Anwendungsdiagramm überarbeiten (ist aktuell Entscheidungsbaum) 
* funktionale/nicht funktionale Anforderungen genauer schreiben (optimal: kein Interpretationsspielraum) 
* im Klassendiagramm sind Pfeile noch falsch herum 

== Aktueller Stand

Erster Meilenstein (Pflichtenheft) wurde erstmal so abgenommen, soll aber noch etwas nachgebessert werden.

